"""End-to-end forge + write tests, including the headline valid-by-construction guarantee."""

from __future__ import annotations

import pytest

from skill_forge import (
    SkillForgeError,
    forge,
    is_kebab_case,
    lint_text,
    render_skill,
    write_skill,
)


@pytest.mark.parametrize(
    "fixture_name", ["python_project", "node_project", "docs_file", "generic_project"]
)
def test_forge_valid_by_construction(fixture_name, request):
    source = request.getfixturevalue(fixture_name)
    draft = forge(source)
    assert is_kebab_case(draft.name)
    rendered = render_skill(draft)
    errors = [p for p in lint_text(rendered, dir_name=draft.name) if p.severity == "error"]
    assert errors == [], errors


def test_forge_name_override(python_project):
    draft = forge(python_project, name="custom-name")
    assert draft.name == "custom-name"


def test_write_skill(tmp_path, python_project):
    draft = forge(python_project)
    path = write_skill(draft, tmp_path)
    assert path == tmp_path / "widget" / "SKILL.md"
    assert path.read_text(encoding="utf-8") == render_skill(draft)

    with pytest.raises(SkillForgeError):
        write_skill(draft, tmp_path)  # refuses to overwrite

    path2 = write_skill(draft, tmp_path, force=True)
    assert path2 == path


def test_write_skill_stays_in_outdir(tmp_path, python_project):
    draft = forge(python_project)
    path = write_skill(draft, tmp_path)
    assert tmp_path in path.parents


def test_forge_body_has_sections(python_project):
    body = forge(python_project).body
    assert "## When to use" in body
    assert "## Commands" in body
    assert "Generated by skill-forge" in body
